# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rekl', '0005_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='object',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rekl.City'),
        ),
        migrations.AddField(
            model_name='object',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='date_modify',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
