# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekl', '0007_auto_20161113_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='pi_address',
            field=models.CharField(default='-', max_length=100, unique=True),
        ),
    ]
